# Generated by Django 5.2.4 on 2026-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0003_remove_project_favorites'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True,
                                         related_name='interested_users',
                                         to='projects.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/',
                                    verbose_name='Аватар'),
        ),
    ]
