# Generated by Django 5.2.4 on 2026-05-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_user_options_alter_user_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True,
                                   unique=True, verbose_name='Номер телефона'),
        ),
    ]
