# Generated by Django 5.2.4 on 2026-05-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, null=True,
                                  verbose_name='Ссылка на GitHub'),
        ),
    ]
