# Generated by Django 5.2.4 on 2026-05-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_user_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=256,
                                   verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=124, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=124, verbose_name='Фамилия'),
        ),
    ]
