# Generated by Django 5.2.4 on 2026-05-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=200,
                                          verbose_name='Название проекта')),
                ('description', models.TextField(blank=True,
                                                 verbose_name='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('github_url',
                 models.URLField(blank=True, verbose_name='Ссылка на GitHub')),
                ('status', models.CharField(
                    choices=[('open', 'Открыт'), ('closed', 'Закрыт')],
                    max_length=6, verbose_name='Статус')),
            ],
        ),
    ]
