# Generated by Django 5.2.4 on 2026-05-29 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='favorites',
        ),
    ]
