# Generated by Django 5.2.4 on 2026-05-29 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0003_remove_project_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       verbose_name='Дата создания проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='owned_projects',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='Автор проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True,
                                         related_name='participated_projects',
                                         to=settings.AUTH_USER_MODEL,
                                         verbose_name='Участники проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(
                choices=[('open', 'Открыт'), ('closed', 'Закрыт')],
                max_length=6, verbose_name='Статус проекта'),
        ),
    ]
