# Generated by Django 5.2.4 on 2026-05-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects',
         '0004_alter_project_created_at_alter_project_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(verbose_name='Ссылка на GitHub'),
        ),
    ]
