# Generated by Django 5.2.4 on 2026-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0005_alter_project_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True,
                                  verbose_name='Ссылка на GitHub'),
        ),
    ]
